# Generated by Django 3.1.5 on 2021-04-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('campaigns', models.CharField(default='mothafucka', editable=False, max_length=100)),
                ('templates', models.CharField(default='mothafucka', editable=False, max_length=100)),
                ('populations', models.CharField(default='mothafucka', editable=False, max_length=100)),
                ('suppressionLists', models.CharField(default='mothafucka', editable=False, max_length=100)),
                ('archives', models.CharField(default='mothafucka', editable=False, max_length=100)),
                ('key', models.CharField(editable=False, max_length=100)),
            ],
        ),
    ]
