# Generated by Django 3.1.5 on 2021-04-09 02:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210409_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('dynamic', models.BooleanField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=55), blank=True, null=True, size=None)),
                ('content', models.CharField(blank=True, max_length=100)),
                ('comments', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('EMAIL', 'Email'), ('LETTER', 'Letter'), ('TWIML', 'Twiml')], max_length=7)),
                ('client', models.CharField(default='http://127.0.0.1:8000/client', editable=False, max_length=100)),
                ('url', models.CharField(default='http://127.0.0.1:8000/templates/<django.db.models.fields.IntegerField>', editable=False, max_length=100)),
            ],
        ),
    ]
