# Generated by Django 3.1.5 on 2021-04-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='url',
            field=models.CharField(default='http://127.0.0.1:8000/templates/', editable=False, max_length=100),
        ),
    ]
