# Generated by Django 3.1.5 on 2021-04-09 05:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20210409_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=55), blank=True, null=True, size=None)),
                ('productionMode', models.BooleanField(default=True)),
                ('communications', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=55), blank=True, null=True, size=None)),
                ('url', models.CharField(default='http://127.0.0.1:8000/communications/', editable=False, max_length=100)),
            ],
        ),
    ]
