# Generated by Django 3.1.5 on 2021-04-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='client',
            field=models.CharField(default='http://127.0.0.1:8000/client', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='url',
            field=models.CharField(default='http://127.0.0.1:8000/campaigns/', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.CharField(blank=True, max_length=4000),
        ),
    ]
