# Generated by Django 3.1.5 on 2021-04-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20210409_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('dataSourceType', models.CharField(choices=[('ManualEmailList', 'Manualemaillist'), ('ManualIDList', 'Manualidlist'), ('ManualCSVList', 'Manualecsvlist'), ('DatabaseQuery', 'Databasequery'), ('WebServiceCall', 'Webservicecall'), ('PredefinedPopulation', 'Predefinedpopulation'), ('AdhocList', 'Adhoclist')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=4000)),
                ('parameterized', models.BooleanField(blank=True, default=False, null=True)),
                ('archived', models.BooleanField(blank=True, default=False, null=True)),
                ('hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('client', models.CharField(default='http://127.0.0.1:8000/client', editable=False, max_length=100)),
                ('manualEmailList', models.JSONField()),
                ('url', models.CharField(default='http://127.0.0.1:8000/populations/', editable=False, max_length=100)),
            ],
        ),
    ]
