# Generated by Django 3.1.5 on 2021-04-09 06:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='population',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=55), blank=True, null=True, size=None),
        ),
    ]
