# Generated by Django 3.1.5 on 2021-04-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20210413_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='destinations',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='email',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='placeholders',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='campaign',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
