# Generated by Django 3.1.5 on 2021-04-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_batch_member_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='url',
            field=models.CharField(default='http://127.0.0.1:8000/messages/', max_length=300),
        ),
    ]
