# Generated by Django 3.1.5 on 2021-04-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20210420_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='url',
            field=models.CharField(default='http://127.0.0.1:8000/communications/', editable=False, max_length=100),
        ),
    ]
