# Generated by Django 3.1.5 on 2021-04-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_message_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='memberId',
            field=models.CharField(max_length=100),
        ),
    ]
