# Generated by Django 3.1.5 on 2021-04-21 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_communication_url'),
        ('client', '0011_auto_20210413_1859'),
    ]

    operations = [
    ]
