# This workflow will install Python dependencies, run tests and lint with a single version of Python.
# This will not deploy to Azure. We will save Azure deployment for when the changes are officially merged into Main.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PGSCM Workflow For Pull Requests To Main

on:
  pull_request:
    branches: [ main ]

env:
  WEBAPP_NAME: 'dispatchlite'

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: postgres1
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: temppassword
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run migrations
      run: |
        python manage.py makemigrations

    - name: Collect static
      run: python manage.py collectstatic
